### ISSUE TITLE
Plugins step fails because rbenv-installer removed the master branch

### ISSUE THREAD

**Issue by asfarley** [zzet/rbenv#152]
I've also logged an issue on the rbenv repo since it's unclear who to blame:

https://github.com/rbenv/rbenv-installer/issues/43

My feeling is this would be more easily corrected by the main rbenv repo, but it could be fixed here if they don't want to rename the branch.

**Comment by zzet** [comment]
Hey @asfarley!

Thank you for the update.

I guess the maintainer of the `rbenv-installer` will not revert back the branch name and changes have to be made in that repository.

Could you prepare a PR?

**Comment by asfarley** [comment]
My apologies, this has already been fixed and I was just out of date.
